name: Format
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  lint:
    name: Test client on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: pnpm install
      - run: pnpm run lint
